weather:
  target: dev
  outputs:
    dev:
      type: "snowflake"
      account: "infinitelambda.eu-west-1"
      private_key_passphrase: "{{ env_var('dvd_test_passphrase')}}"
      private_key_path: /root/.ssh/rsa_key_david_sf.p8
      user: "DAVIDSANCHEZ" 
      role: "ROLE_DVD_TEST" 
      database: "TEST_DVD_PIPELINE" 
      warehouse: "WAREHOUSE_DVD_TEST" 
      schema: "re_data_test"
      threads: 4
      client_session_keep_alive: False
    test:
      type: "snowflake"
      account: "infinitelambda.eu-west-1"
      private_key_passphrase: "{{ env_var('dvd_test_passphrase')}}"
      private_key_path: "{{ env_var('SSH_KEY')}}"
      user: "DAVIDSANCHEZ" 
      role: "ROLE_DVD_TEST" 
      database: "{{ env_var('pr_ci_db') }}"
      warehouse: "WAREHOUSE_DVD_TEST" 
      schema: "TESTING_CI"
      threads: 4
      client_session_keep_alive: False