version: 2

sources:
  - name: standard_tile
    database: secure_share_weathersource_1641488329256
    tables:
      - name: climatology_day
        columns:
          - name: postal_code
          - name: country
          - name: doy_std
          - name: avg_of__daily_min_temperature_air_f
          - name: std_of__daily_min_temperature_air_f
          - name: avg_of__daily_avg_temperature_air_f
          - name: std_of__daily_avg_temperature_air_f
          - name: avg_of__daily_max_temperature_air_f
          - name: std_of__daily_max_temperature_air_f
          - name: avg_of__daily_min_temperature_wetbulb_f
          - name: std_of__daily_min_temperature_wetbulb_f
          - name: avg_of__daily_avg_temperature_wetbulb_f
          - name: std_of__daily_avg_temperature_wetbulb_f
          - name: avg_of__daily_max_temperature_wetbulb_f
          - name: std_of__daily_max_temperature_wetbulb_f
          - name: avg_of__daily_min_temperature_dewpoint_f
          - name: std_of__daily_min_temperature_dewpoint_f
          - name: avg_of__daily_avg_temperature_dewpoint_f
          - name: std_of__daily_avg_temperature_dewpoint_f
          - name: avg_of__daily_max_temperature_dewpoint_f
          - name: std_of__daily_max_temperature_dewpoint_f
          - name: avg_of__daily_min_temperature_feelslike_f
          - name: std_of__daily_min_temperature_feelslike_f
          - name: avg_of__daily_avg_temperature_feelslike_f
          - name: std_of__daily_avg_temperature_feelslike_f
          - name: avg_of__daily_max_temperature_feelslike_f
          - name: std_of__daily_max_temperature_feelslike_f
          - name: avg_of__daily_min_humidity_relative_pct
          - name: std_of__daily_min_humidity_relative_pct
          - name: avg_of__daily_avg_humidity_relative_pct
          - name: std_of__daily_avg_humidity_relative_pct
          - name: avg_of__daily_max_humidity_relative_pct
          - name: std_of__daily_max_humidity_relative_pct
          - name: avg_of__daily_min_humidity_specific_gpkg
          - name: std_of__daily_min_humidity_specific_gpkg
          - name: avg_of__daily_avg_humidity_specific_gpkg
          - name: std_of__daily_avg_humidity_specific_gpkg
          - name: avg_of__daily_max_humidity_specific_gpkg
          - name: std_of__daily_max_humidity_specific_gpkg
          - name: avg_of__daily_min_pressure_surface_mb
          - name: std_of__daily_min_pressure_surface_mb
          - name: avg_of__daily_avg_pressure_surface_mb
          - name: std_of__daily_avg_pressure_surface_mb
          - name: avg_of__daily_max_pressure_surface_mb
          - name: std_of__daily_max_pressure_surface_mb
          - name: avg_of__daily_min_pressure_mean_sea_level_mb
          - name: std_of__daily_min_pressure_mean_sea_level_mb
          - name: avg_of__daily_avg_pressure_mean_sea_level_mb
          - name: std_of__daily_avg_pressure_mean_sea_level_mb
          - name: avg_of__daily_max_pressure_mean_sea_level_mb
          - name: std_of__daily_max_pressure_mean_sea_level_mb
          - name: avg_of__daily_min_wind_speed_10m_mph
          - name: std_of__daily_min_wind_speed_10m_mph
          - name: avg_of__daily_avg_wind_speed_10m_mph
          - name: std_of__daily_avg_wind_speed_10m_mph
          - name: avg_of__daily_max_wind_speed_10m_mph
          - name: std_of__daily_max_wind_speed_10m_mph
          - name: avg_vec_of__daily_avg_vec_wind_direction_10m_deg
          - name: avg_vec_of__daily_avg_vec_wind_direction_80m_deg
          - name: avg_vec_of__daily_avg_vec_wind_direction_100m_deg
          - name: avg_of__pos_daily_tot_precipitation_in
          - name: frq_of__pos_daily_tot_precipitation_in_pct
          - name: std_of__pos_daily_tot_precipitation_in
          - name: frq_of__daily_tot_precipitation_zero_in_pct
          - name: frq_of__daily_tot_precipitation_001_010_in_pct
          - name: frq_of__daily_tot_precipitation_010_025_in_pct
          - name: frq_of__daily_tot_precipitation_025_050_in_pct
          - name: frq_of__daily_tot_precipitation_050_100_in_pct
          - name: frq_of__daily_tot_precipitation_100_250_in_pct
          - name: frq_of__daily_tot_precipitation_250_500_in_pct
          - name: frq_of__daily_tot_precipitation_500_gtr_in_pct
          - name: avg_of__pos_daily_tot_snowfall_in
          - name: frq_of__pos_daily_tot_snowfall_in_pct
          - name: std_of__pos_daily_tot_snowfall_in
          - name: pct_frq_of__daily_tot_snowfall_zero_in_pct
          - name: pct_frq_of__daily_tot_snowfall_001_010_in_pct
          - name: pct_frq_of__daily_tot_snowfall_010_025_in_pct
          - name: pct_frq_of__daily_tot_snowfall_025_050_in_pct
          - name: pct_frq_of__daily_tot_snowfall_050_100_in_pct
          - name: pct_frq_of__daily_tot_snowfall_100_150_in_pct
          - name: pct_frq_of__daily_tot_snowfall_150_250_in_pct
          - name: pct_frq_of__daily_tot_snowfall_250_gtr_in_pct
          - name: avg_of__pos_daily_snowdepth_in
          - name: std_of__pos_daily_snowdepth_in
          - name: avg_of__daily_min_cloud_cover_tot_pct
          - name: std_of__daily_min_cloud_cover_tot_pct
          - name: avg_of__daily_avg_cloud_cover_tot_pct
          - name: std_of__daily_avg_cloud_cover_tot_pct
          - name: avg_of__daily_max_cloud_cover_tot_pct
          - name: std_of__daily_max_cloud_cover_tot_pct
          - name: avg_of__daily_min_radiation_solar_total_wpm2
          - name: std_of__daily_min_radiation_solar_total_wpm2
          - name: avg_of__daily_avg_radiation_solar_total_wpm2
          - name: std_of__daily_avg_radiation_solar_total_wpm2
          - name: avg_of__daily_max_radiation_solar_total_wpm2
          - name: std_of__daily_max_radiation_solar_total_wpm2
          - name: avg_of__daily_tot_radiation_solar_total_wpm2
          - name: std_of__daily_tot_radiation_solar_total_wpm2

      - name: forecast_day
        config:
          re_data_monitored: true
          re_data_time_filter: time_created
          re_data_anomaly_detector:
            name: modified_z_score
            threshold: 3.5
        columns:
          - name: postal_code
          - name: country
          - name: time_init_utc
          - name: date_valid_std
          - name: doy_std
          - name: min_temperature_air_2m_f
          - name: avg_temperature_air_2m_f
          - name: max_temperature_air_2m_f
          - name: min_temperature_wetbulb_2m_f
          - name: avg_temperature_wetbulb_2m_f
          - name: max_temperature_wetbulb_2m_f
          - name: min_temperature_dewpoint_2m_f
          - name: avg_temperature_dewpoint_2m_f
          - name: max_temperature_dewpoint_2m_f
          - name: min_temperature_feelslike_2m_f
          - name: avg_temperature_feelslike_2m_f
          - name: max_temperature_feelslike_2m_f
          - name: min_temperature_windchill_2m_f
          - name: avg_temperature_windchill_2m_f
          - name: max_temperature_windchill_2m_f
          - name: min_temperature_heatindex_2m_f
          - name: avg_temperature_heatindex_2m_f
          - name: max_temperature_heatindex_2m_f
          - name: min_humidity_relative_2m_pct
          - name: avg_humidity_relative_2m_pct
          - name: max_humidity_relative_2m_pct
          - name: min_humidity_specific_2m_gpkg
          - name: avg_humidity_specific_2m_gpkg
          - name: max_humidity_specific_2m_gpkg
          - name: min_pressure_2m_mb
          - name: avg_pressure_2m_mb
          - name: max_pressure_2m_mb
          - name: min_pressure_mean_sea_level_mb
          - name: avg_pressure_mean_sea_level_mb
          - name: max_pressure_mean_sea_level_mb
          - name: min_wind_speed_10m_mph
          - name: avg_wind_speed_10m_mph
          - name: max_wind_speed_10m_mph
          - name: avg_wind_direction_10m_deg
          - name: min_wind_speed_80m_mph
          - name: avg_wind_speed_80m_mph
          - name: max_wind_speed_80m_mph
          - name: avg_wind_direction_80m_deg
          - name: min_wind_speed_100m_mph
          - name: avg_wind_speed_100m_mph
          - name: max_wind_speed_100m_mph
          - name: avg_wind_direction_100m_deg
          - name: tot_precipitation_in
          - name: tot_snowfall_in
          - name: min_cloud_cover_tot_pct
          - name: avg_cloud_cover_tot_pct
          - name: max_cloud_cover_tot_pct
          - name: min_radiation_solar_total_wpm2
          - name: avg_radiation_solar_total_wpm2
          - name: max_radiation_solar_total_wpm2
          - name: tot_radiation_solar_total_wpm2
          - name: probability_of_precipitation_pct
          - name: probability_of_snow_pct

      - name: history_day
        columns:
          - name: postal_code
          - name: country
          - name: date_valid_std
          - name: doy_std
          - name: min_temperature_air_2m_f
          - name: avg_temperature_air_2m_f
          - name: max_temperature_air_2m_f
          - name: min_temperature_wetbulb_2m_f
          - name: avg_temperature_wetbulb_2m_f
          - name: max_temperature_wetbulb_2m_f
          - name: min_temperature_dewpoint_2m_f
          - name: avg_temperature_dewpoint_2m_f
          - name: max_temperature_dewpoint_2m_f
          - name: min_temperature_feelslike_2m_f
          - name: avg_temperature_feelslike_2m_f
          - name: max_temperature_feelslike_2m_f
          - name: min_temperature_windchill_2m_f
          - name: avg_temperature_windchill_2m_f
          - name: max_temperature_windchill_2m_f
          - name: min_temperature_heatindex_2m_f
          - name: avg_temperature_heatindex_2m_f
          - name: max_temperature_heatindex_2m_f
          - name: min_humidity_relative_2m_pct
          - name: avg_humidity_relative_2m_pct
          - name: max_humidity_relative_2m_pct
          - name: min_humidity_specific_2m_gpkg
          - name: avg_humidity_specific_2m_gpkg
          - name: max_humidity_specific_2m_gpkg
          - name: min_pressure_2m_mb
          - name: avg_pressure_2m_mb
          - name: max_pressure_2m_mb
          - name: min_pressure_tendency_2m_mb
          - name: avg_pressure_tendency_2m_mb
          - name: max_pressure_tendency_2m_mb
          - name: min_pressure_mean_sea_level_mb
          - name: avg_pressure_mean_sea_level_mb
          - name: max_pressure_mean_sea_level_mb
          - name: min_wind_speed_10m_mph
          - name: avg_wind_speed_10m_mph
          - name: max_wind_speed_10m_mph
          - name: avg_wind_direction_10m_deg
          - name: min_wind_speed_80m_mph
          - name: avg_wind_speed_80m_mph
          - name: max_wind_speed_80m_mph
          - name: avg_wind_direction_80m_deg
          - name: min_wind_speed_100m_mph
          - name: avg_wind_speed_100m_mph
          - name: max_wind_speed_100m_mph
          - name: avg_wind_direction_100m_deg
          - name: tot_precipitation_in
          - name: tot_snowfall_in
          - name: tot_snowdepth_in
          - name: min_cloud_cover_tot_pct
          - name: avg_cloud_cover_tot_pct
          - name: max_cloud_cover_tot_pct
          - name: min_radiation_solar_total_wpm2
          - name: avg_radiation_solar_total_wpm2
          - name: max_radiation_solar_total_wpm2
          - name: tot_radiation_solar_total_wpm2